### ISSUE TITLE
Substituição da coordenação do  FEMUG AM

### ISSUE THREAD

**Issue by Kirmayrtomaz** [femug/femug#100]
Oi pessoal, 
recentemente estou ajudando a criar os eventos de FEMUG em manaus - am.

Gostaria de pedir a alteração do membro responsável e organização daqui de manaus. Já conversei com o @ayr-ton sobre essa situação. 

 Já conseguimos organizar um evento no dia 13 de agosto em manaus e estamos a todo vapor para fazer um próximo. 

Algumas referências 

 [site](http://frontendam.github.io/femug)
 [facebook](https://www.facebook.com/femugam/)
 [eventick](https://www.eventick.com.br/femugam)

**Comment by danielfilho** [comment]
PR?

**Comment by Kirmayrtomaz** [comment]
AM

**Comment by danielfilho** [comment]
@Kirmayrtomaz aguardo o PR (pull request) com as mudanças.
/ping @ayr-ton

**Comment by ayr-ton** [comment]
@dancasttro Copy that! Já confirmei a mudança pelo facebook com o Kirma o/
Valeu pela força, @Kirmayrtomaz cuide bem da comunidade de Manaus e todo sucesso nos meetups o/
Nos vemos quando eu visitar a cidade.

Se precisar de acesso em algo específico é só me pingar, mas pode atualizar os links no json e nos mds, os forms anfitriões e as listas antigas não estão sendo mais utilizadas.
