### ISSUE TITLE
Melhorar Abordagem

### ISSUE THREAD

**Issue by mauriciosoares** [femug/femug#73]
Fala galera,

Eu não sou a pessoa ideal para sugerir essa melhoria, também porque eu fui a poucos femugs...

Mas queria deixar a ideia na mesa para discussão...

Hoje pelo que eu percebo, o femug eh meio que uma "roda" onde cada um fala de cada vez, e todos escutam... (isso quando nao tem mini palestras), dessa maneira todo mundo participa da mesma discussão.

Eu queria sugerir criar rodas menores, com mais assuntos programados para os femugs, e esses assuntos rolarem em paralelo... 

__Por que isso?__

Muitas vezes o assunto que está rolando não interessa a 100% das pessoas (o que já aconteceu comigo), dessa maneira cada um escolhia qual assunto ela quer participar, e só fala com pessoas que querem falar daquele assunto em específico também. Acho que isso pode ser mais produtivo e agregar muito mais conhecimento para os participantes.

O que acham?

**Comment by rafaelrinaldi** [comment]
@mauriciosoares A ideia dos encontros é rodar entre dois temas previamente sugeridos e votados pela comunidade. Em teoria, quem vai a um encontro já sabe do que irá ser discutido.

Eu acho que criar rodas paralelas pode inclusive atrapalhar um pouco no foco das discussões. Motivos:

  1. Raramente os encontros tem mais do que `30` pessoas, que é um número relativamente baixo para se dividir em vários grupos;
  2. Somos "refens" da estrutura do lugar que esta hospedando o encontro. Na maioria não são lugares tão grandes. Fico imaginando vários grupos separados, cada um discutindo sobre um tema diferente, e o barulho que ficaria...
  3. A frequência dos encontros é boa, então se um assunto não interessar, você pode sugerir no forum e no proximo encontro debater sobre o tema que voce quer (poucas pessoas sugerem temas; na verdade, nos últimos encontros eu que inventei de última hora por falta de sugestões. Então as chances de um novo tema sugerido virar pauta de um encontro é bem alta)
  4. Você comentou do lance de ter participado de encontros onde o tema atual nao te interessava, mas imagina o contrario... Uma pessoa vai ao encontro pela primeira vez e dois grupos em paralelo discutem temas que ela gostaria de participar. Essa pessoa ficaria dividida e teria de optar por um dos dois;
  5. No mundo do front-end existe muita coisa acontecendo o tempo todo, dar uma filtrada nisso é um dos pontos fortes do FEMUG na minha opiniao. Criar rodas paralelas só aumentaria o "noise", que é o que já vivemos diariamente tentando consumir informações sobre essa area.

Essas são as minhas considerações, mas muito obrigado pelas sugestões cara! E  veja se aparece em mais encontros `#sdds`.

> Ps.: Tudo o que falei é baseado na minha experiência ajudando a organizar o FEMUG-SP especificamente.

**Comment by mauriciosoares** [comment]
Legal @rafaelrinaldi, seus pontos são extremamente válidos...

Mas acho que um outro motivo desse formato ser meio falho é o fato de nos femugs, de 30 pessoas, acaba que no final umas 10 pessoas falando e outras 20 ouvindo (pelo menos no que eu presenciei, isso pode nao ser uma regra).

Eu mesmo por ser alguém mais tímido não expressei minha opinião, porque é extremamente intimidador você falar algo para 30 pessoas que você nem conhece... Grupos menores ajudaria ao pessoal participar mais das conversas, o que resulta em muito mais conteúdo sendo compartilhado.

O fator espaço e "noise" é algo real, e eu não tinha levado em consideração, em áreas menores não da pra seguir essa abordagem...

Mas deixo a ideia para fazer um teste A/B em locais que tem a possibilidade de separar em grupos menores, e ver o que o pessoal acha... tipo um `femug/B`, vocês escolhem 2 assuntos a mais, e a galera faz 2 rodas ao invés de uma...

Bom, vejam a possibilidade/viabilidade disso... vai que rola né hahaha

Valeu, se quiser dar um close na issue fique a vontade.

**Comment by rafaelrinaldi** [comment]
@mauriciosoares Essa lance da participação é um problema real e que tentamos melhorar todos os encontros... No geral as pessoas (principalmente as que estão participando pela primeira vez) são mais introvertidas e acabam não se expressando tanto.

No começo era bem mais visível isso, hoje já melhoramos muito mas ainda há espaço pra otimizar esse ponto... Talvez a sua ideia seja interessante de aplicar e testar isso. Gostei do conceito de teste A/B hahaha.

**Comment by mauriciosoares** [comment]
:heart: 

Se quiser fechar essa issue fique a vontade...

Ou de repente deixar aberto para os outros organizadores darem uma olhada tbm

:)

**Comment by danielfilho** [comment]
baita dica @mauriciosoares. curti demais. mas temos que levar em consideração alguns pontos:

 seu ponto de vista é super válido e, apesar de ser o criador da iniciativa e ajudar a ela se espalhar pelo Brasil todo (já estamos em mais de 15 cidades :scream:), acredito que suas dicas são dadas em cima do FEMUG-SP, que é o que eu conheço também, apesar de tudo isso :grimacing: 

o formato que você citou, é o formato que rola com o FEMUG-SP (novamente), mas a gente já teve palestras, a gente já teve code-clinic (ou pelo menos a intenção, haha), já tivemos showcase e várias outras coisas.

a gente nunca teve a idéia de fazer várias pequenas rodas, mas eu realmente não gosto desse formato pelo mesmo motivo que não gosto de eventos com mais de uma trilha. nos últimos dois meses estou pensando em umas coisas e vou começar a reformular aos poucos a documentação do FEMUG.

sobre o assunto não interessar 100% das pessoas: esse é um dos motivos que fazemos a votação. é impossível agradar todo mundo (e te garanto que esse não é o objetivo). caso o assunto selecionado não seja de interesse, a pessoa pode ceder a vaga dela pra outra que não entrou :wink:. ainda, podemos melhorar a mecânica disso, fazendo a votação da pauta de maneira pública, e depois fazendo o sorteio entre quem votou. ao votar na pauta, você está automaticamente dizendo que quer participar do sorteio de vagas. mas isso pode ter um agravante: a maioria vota em A, mas a maioria sorteada votou em B, então a galera que vai não é a mesma que votou no tópico vencedor.

mas uma coisa BEM legal que vc levantou e a gente pode trabalhar é tentar bolar uma condicional mais ou menos assim:

> se o encontro tiver mais de 20 pessoas, este pode funcionar melhor com uma apresentação de 30 até 45 minutos e logo depois, o tempo restante se discute o assunto. Ou com duas apresentações distintas, ocupando todo o tempo, fazendo uma pausa de 15 minutos entre as apresentações.

acho bem válida essa condicional :point_up: e já podemos mandar bronca no próximo com isso.

**Comment by mauriciosoares** [comment]
Boa @danielfilho, O lance da condicional pode ser algo interessante também.

Eu só quis jogar a ideia na mesa msm, se vocês conseguirem desenvolve-la em algo que se encaixe no formato do FEMUG, pra mim já é bem legal 🐑

**Comment by danielfilho** [comment]
valeu demais por essa thread, Mauricio. acredito que estamos melhorando cada vez mais nesse aspecto, graças a você também!

a issue será fechada, mas não travada :smile: 

:kiss:

**Comment by mauriciosoares** [comment]
:heartbeat:
