### ISSUE TITLE
Criação do FEMUG-RN

### ISSUE THREAD

**Issue by henricavalcante** [femug/femug#75]
Estou mudando um meetup que já existia aqui no RN para o modelo FEMUG, antes o evento era apenas destinado ao JavaScript e agora a Front-end em geral.

http://www.meetup.com/FEMUG-RN

**Comment by henricavalcante** [comment]
@danielfilho os moderadores podem ser alterado ao longo do tempo? Inicialmente vou começar apenas com um amigo e após o primeiro evento já vou tentar colocar mais gente para ajudar.

**Comment by danielfilho** [comment]
podem sim @henricavalcante, no esquema de pull-request :)

**Comment by danielfilho** [comment]
@henricavalcante e esse femug? sai ou não sai? :D
manda o PR com as infos!

**Comment by henricavalcante** [comment]
@danielfilho opa, vou agilizar sim cara, estou tentando juntar gente para me ajudar com as coisas aqui, a página do meetup já tem bastante gente interessada.

**Comment by danielfilho** [comment]
tamo no aguardo :D
