### ISSUE TITLE
FEMUG-RJ - Link Errado

### ISSUE THREAD

**Issue by jeanpaulo** [femug/femug#85]
Falae galera.
O link do FEMUG-RJ não está correto. Está com o mesmo link do FEMUG-ABC (https://goo.gl/jvfyUb).
Não tenho o endereço correto :/

Alguém pode corrigir?
Abraços!

**Comment by afonsopacifer** [comment]
Opa, arrumei aqui e mandei agora no PR #86
Vlw @jeanpaulo :+1:

**Comment by lucasmazza** [comment]
@afonsopacifer obrigado pela correção :heart:

**Comment by afonsopacifer** [comment]
@lucasmazza Tamo junto ;)
