### ISSUE TITLE
Andamento dos capítulos

### ISSUE THREAD

**Issue by danielfilho** [femug/femug#87]
Querid@s @femug/moderators 

Como está a atividade do capítulo de vocês?

Gostaria de entender, desde quando foi criado o capítulo, quantas reuniões já tiveram. Estão precisando de alguma ajuda com algo? Dicas? Anseios? Contem pra gente se ajudar :wink:

**Comment by raphamorim** [comment]
Opa, aqui no RJ estamos indo para terceira edição (dia 23 janeiro). Por enquanto não, mas se houver algo eu notifico sim :)))

Sobre as atividades:
Vamos fazer o primeiro encontro da comunidade de frontend na baixada do RJ, algo inédito já que os eventos restringem se apenas a zona sul, barra da tijuca e centro do Rio.

Sobre a programação da atividade; A ideia é cada um que vai levar algo que está trabalhando ou está aprendendo e fazer uma apresentação de até 15min sobre aquilo. Fazemos um círculo e pós apresentação há a possibilidade de debatermos o assunto ou deixar para o final.

Pós-evento: Rola aquela social num bar próximo ao local.

**Comment by danielfilho** [comment]
que sensacional @raphamorim. eu sempre quis um femug-rj, tinha certeza que quando rolasse ia ser um dos mais ativos. parabens pra galera daí e pela sua proatividade :heart:

**Comment by raphamorim** [comment]
:heart: Fica o convite @danielfilho para aparecer no próximo :))

**Comment by joselitojunior1** [comment]
Aqui em Pernambuco estamos indo para a terceira edição também, ainda sem
data marcada, mas com local já definido, que será na Liferay.

A estrutura aqui é um meetup tradicional com algumas palestras. Estamos
incentivando bastante as próprias pessoas das comunidades a falarem no
"palco".

Ainda estamos começando, mas já tá dando algum resultado (:

**Comment by oieduardorabelo** [comment]
Por hora eu acredito que o FEMUG-VP está parado!

Eu estava discutindo isso essa semana, junto com o @michelamaral (que apesar de não estar na lista de moderadores, praticamente atuou como um),

Os esforços locais estão sendo aplicados em outros encontros, como GD*, FrontInVale,

Outros moderadores como, @reuellopes, estão atuando junto com o @michelamaral em outros encontros,

Devido a falta de recursos/esforços, acredito eu que o FEMUG-VP poderá ser desativado em favor dos mesmos moderadores estarem empenhados em outros encontros.

**Comment by marcio** [comment]
Aqui em Campinas estamos parados, tivemos algumas tentativas frustradas de
encontro, aqui o problema nem é o local, e sim o empenho da galera mesmo.

A galera nem na lista é ativa. Se alguém tiver alguma dica, estou aceitando.

Abraço!



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.1.1&source=email_footer_2] On Mon, Jan 18, 2016 at 7:31 PM, Daniel R. C. Filho < notifications@github.com [notifications@github.com] > wrote:
Querid@s @femug/moderators [https://github.com/orgs/femug/teams/moderators]

Como está a atividade do capítulo de vocês?

Gostaria de entender, desde quando foi criado o capítulo, quantas reuniões já
tiveram. Estão precisando de alguma ajuda com algo? Dicas? Anseios? Contem pra
gente se ajudar:wink: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f609.png]

**Comment by nandomoreirame** [comment]
Opa @danielfilho !!

Aqui em Curitiba está indo como esperado, estamos agendando o terceiro encontro para fevereiro, pulamos Janeiro para organizar melhor e não ter aquela correria de último dia :smile:

Os dois primeiros foram super legais, com mesa redonda e tudo \o/

Estamos vendo alguns locais e palestrantes para os próximos meses, e já deixo o convite: _Quem tiver passando por Curitiba nos próximos meses e quiser dar uma "palhinha" pra nós aqui só da um toque que já agendamos uma data_ :wink:

Abrax!

**Comment by woliveiras** [comment]
Fala galera!

Aqui no ABC estamos indo para a [sexta](http://abc.femug.com/t/femug-abc-6-testes-de-software) edição dia 23. Estamos indo bem, a galera participa bastante no [Slack](slackfemugabc.herokuapp.com) e estamos desenvolvendo várias maneiras de interagir, como uma playlist colaborativa no [Spotfy](https://play.spotify.com/user/12145853280/playlist/5en9pVrOEdPGSbAzVh2voc) (ideia de um de nossos membros). Só está difícil trazer todo mundo do [Meetup](http://www.meetup.com/pt-BR/femug-abc/) para o [abc.femug.com](abc.femug.com), pois alguns preferem a maneira como o Meetup.com funciona.
Rola uns Hackathons, Hangouts e Dojos também, mas só marcamos os encontros mensais esse ano, logo menos vai rolar tudo isso de novo.
Pra esse ano estou tentando organizar um evento grande aqui, algo de mais de 2 horas em um local legal pra atrair mais gente pro grupo e mostrar pro povo que no ABC tem desenvolvedor pra caramba! kkkkk
Encontramos uma pessoa que nos ajuda muito sedendo o espaço dele, então estamos aproveitando a oportunidade pra fazer sempre lá.
Creio que está dando tão certo aqui por conta dos membros serem super ativos. A galera ajuda muito.  Alguém sempre tem uma ideia legal pra gente.

**Comment by cironunes** [comment]
Aqui em MG só rolou um encontro por enquanto e não tem uma data para o próximo. Estou de mudança e não vou poder continuar organizando os encontros então seria legal se alguém pudesse tomar frente.

**Comment by guuibayer** [comment]
Salve!
Bom aqui em Maringá, nosso primeiro encontro acontecerá agora dia 23/01, em que as inscrições acabaram muito rápido! será algumas talks, mais pretendemos fazer encontros mais dinâmicos em que todos participem.

A galera também participa bastante no [Slack](https://devparana.herokuapp.com), nele estamos reunindo uma enorme galera do Paraná, e impulsionar a galera a se aproximar mais!

**Comment by joselitojunior1** [comment]
@woliveiras aqui rolou a mesma coisa referente ao site do Meetup. Usamos de início o discourse, mas a adoção foi ínfima. Em 2016 decidimos usar o Meetup pois é assim que a galera curte mais.

**Comment by woliveiras** [comment]
É tenso @joselitojunior1, pois no Discourse rola umas interações nos tópicos. Já no Meetup, alguns nem sabiam que tem forum! kkkkk

**Comment by danielfilho** [comment]
## Parabéns

pessoal, parabéns pro @joselitojunior1, @guuibayer e @nandomoreirame que estão tocando os capítulos. é uma tarefa HIPER árdua, mas é recompensador. a gente acaba aprendendo mais que todo mundo, por tocarmos iniciativas como essa. se precisarem de qualquer ajuda, abram uma issue aqui e pinga os moderadores :)

## Destaque
@woliveiras, o que vocês estão fazendo no FEMUG-ABC é sensacional. SUPER parabéns pra toda a galera envolvida no FEMUG. morro de vontade de ir um dia, mas acompanho a atividade e vejo que são super movimentados.

## Discourse / Google Groups / Meetup.com / Whatever

o mais legal de tudo é deixar agnóstico a tecnologia usada, plataforma e tudo mais. podem usar foruns, meetup.com, discourse ou o que for. o que importa é trazer a galera.

o que podem tentar fazer, é cross-post: usar, por exemplo, o meetup.com pra RSVP enquanto o conteúdo e todo o resto é postado, combinado e tudo mais no discourse. assim quem nao quer participar da ~comunidade~ em si, usa só o meetup, e assim por diante. temos que focar em facilitar. e se a maioria gosta de uma ferramenta, é só fazer as adequações ;)

## Desativar

No próximo release, vou desativar os seguintes capítulos:

- [ ] @oieduardorabelo - femug-vp
- [ ] @marcio - femug-cps
- [ ] @cironunes - femug-mg

Se estiverem de acordo, apenas cliquem na caixa ao lado do seu nome, caso contrário, vamos conversar em uma issue específica pro seu capítulo pra tentarmos resgatar, ok?

## Pedido

vamos tentar deixar a listagem (markdown e json) o mais atualizado possível, ok pessoal? 

## Domínios:

Eu também estou pagando um serviço de [DNS](https://dnsimple.com/r/32581a1db899ea) pra todos termos URLs confiáveis, como `*.femug.com`. Aqui vem a lista:

- [abc.femug.com](http://abc.femug.com)
- [al.femug.com](http://al.femug.com)
- [am.femug.com](http://am.femug.com)
- [ce.femug.com](http://ce.femug.com)
- [cps.femug.com](http://cps.femug.com)
- [cwb.femug.com](http://cwb.femug.com)
- [df.femug.com](http://df.femug.com)
- [go.femug.com](http://go.femug.com)
- [li.femug.com](http://li.femug.com)
- [ma.femug.com](http://ma.femug.com)
- [mg.femug.com](http://mg.femug.com)
- [mga.femug.com](http://mga.femug.com)
- [pe.femug.com](http://pe.femug.com)
- [rj.femug.com](http://rj.femug.com)
- [rs.femug.com](http://rs.femug.com)
- [sc.femug.com](http://sc.femug.com)
- [sm.femug.com](http://sm.femug.com)
- [sp.femug.com](http://sp.femug.com)
- [vp.femug.com](http://vp.femug.com)

todas essas URLs apontam pra url cadastrada no json ;)

> se tiver interesse em assinar um serviço de DNS, assine o DNSimple a partir deste link: [https://dnsimple.com/r/32581a1db899ea](), que você estará ajudando o FEMUG :wink:

**Comment by diogomoretti** [comment]
@danielfilho e todos:

Aqui em Floripa chegamos a fazer o primeiro encontro com o nome **FEMUG-SC** em Abril/2014 (há quase 2 anos). Como na época já usávamos o nome **FloripaJS** para nos referir a comunidade local (inclusive no primeiro FEMUG falamos que era uma organização do FloripaJS), fomos então fazer o próximo encontro.

Este próximo encontro só foi acontecer em Setembro/2014, e então com o nome de [FloripaJS Meetup](http://www.meetup.com/floripajs) (que existe e nos encontramos até hoje – já teve 9 encontros e no grupo do meetup.com temos mais de 400 desenvolvedores inscritos).

Desde então (Setembro/2014) a "marca" **FloripaJS** se tornou cada vez mais forte e caindo no costume das pessoas. O fato é que já temos um encontro aqui chamado **FloripaJS Meetup** que é originário do FEMUG.

Não sei o que vocês acham... De repente o FEMUG (sc.femug.com) apontar pro floripajs.org ou algo parecido, já que esta comunidade e este encontro está mais do que consolidade na comunidade local.

=]

**Comment by oieduardorabelo** [comment]
@diogomoretti , bacana a idéia do redirecionamento!

Realmente o FrontInVale e o GDG estão mais consolidados na região do Vale do Paraíba,

O @michelamaral, junto do @reuellopes e outros, estão empenhados nos outros encontros!

Caso seja possível o redirecionamento, tem o meu :+1: ! (aí não vou marcar a caixinha Daniel! :P)

**Comment by juarezpaf** [comment]
Por aqui em Alagoas começamos utilizando o Meetup.com mas a adoção foi ínfima também, temos duas comunidades fortes aqui realizando encontros mensais, o Maceió Dev Meetup e o GDG Maceió, daí o que estamos fazendo fazer um Meetup específico para o FEMUG-AL dentro do GDG Maceió.
Fizemos o #1 FEMUG-AL no dia 14 de Maio de 2015 https://www.facebook.com/events/1420405181613753/ junto com uma outra iniciativa nossa que é o English Tech Talks, ou seja, todas palestras foram em Inglês e toda discussão também, nos próximos dois encontros fizemos no estilo de Hands-on com Firebase e Polymer.
Vamos para o #4 encontro em breve que será provavelmente de AngularJS.

Acredito que é uma idea interessante essa questão de colaboração das iniciativas locais.
Aguardo o feedback com relação ao ponto levantado também pelo @diogomoretti 

:smile:

**Comment by danielfilho** [comment]
@diogomoretti pelo que entendi estão seguindo com outro meetup que não o FEMUG. posso fechar o capítulo? sobre o que acho em relação a direcionar: não. não tem nexo (vide abaixo)

@diogomoretti @oieduardorabelo não acho que faça sentido redirecionar. não tem porque, se a URL não foi divulgada ainda, a não ser nessa issue :wink: 

@juarezpaf 1 FEMUG em 8 meses é tenso :disappointed: 

o FEMUG é um documento que ajuda quem quer começar um meetup, se você já tem uma comunidade consolidada no assunto, não tem muito sentido segmentar, acho que tem mesmo é que juntar sem concorrer, mas sim unir :grin:  

outro ponto: não existe problema ALGUM em acabar/fechar um capítulo do FEMUG. não estamos aqui pra fazer número, mas sim pra ajudar. se não estamos ajudando com os FEMUGs. é só falar que não rola e passar a bola, ou fechar o capítulo :wink: 

> ps: claro, existem casos onde, mesmo com comunidade local, o femug se faz valer. ex: um grupo que já exista no mesmo assunto, onde a organização se mantem fechada, ou com casos de abusos, quebras de conduta etc.

**Comment by oieduardorabelo** [comment]
Pode passar a régua no FEMUG-VP então! :tada:

**Comment by oieduardorabelo** [comment]
Tentei clicar no checkbox lá e não foi! :stuck_out_tongue_closed_eyes:

**Comment by cironunes** [comment]
Tbm tentei clicar e não foi. Pode desativar.

[]s

**Comment by diogomoretti** [comment]
@danielfilho, nesse caso sim, pode deixar stand-by ou whatever parecido a de SC.

**Comment by matheuspoleza** [comment]
@danielfilho Estamos organizando o primeiro meetup para fevereiro já. Temos 70 pessoas no meetup.com e a galera ta ansiosa por começar algo aqui, ainda não temos uma comunidade forte e consolidade de front, estamos puxando com o FEMUG para rolar isso.

Amanhã defino os últimos detalhes com a empresa que vai ceder o local e já abro o evento no _eventick_ .

**Comment by luisfmsouza** [comment]
@danielfilho @marcio aqui em Campinas, pouco depois da tentavida do FEMUG, o pessoal criou o [Campinas Front-End Meetup](https://github.com/campinas-front-end-meetup/meetups), tem o mesmo objetivo e preenche o mesmo espaço do FEMUG, mas com o outro nome.

Já rolaram 4 eventos e o pessoal é bem ativo no Slack, entra lá @marcio

**Comment by danielfilho** [comment]
legal demais @matheuspoleza e @luisfmsouza! :grimacing:

**Comment by nandomoreirame** [comment]
O 3º FEMUG-CWB está agendado para 13/02 (sábado) na [Nex Coworking](http://www.nexcoworking.com.br/)... Nós precisamos de palestrantes, se alguém estiver passando por aqui no dia 13 podemos conversar e marcar uma palestrinha :smile:

**Comment by marcio** [comment]
Legal @luisfmsouza, apenas como dica, poderiam ter divulgado lá na lista neh!!? :stuck_out_tongue_winking_eye: 

@danielfilho acho que isso fecha o capítulo em cps, certo? Abraço!

**Comment by NandoKstroNet** [comment]
Fala galera! Desde que abrimos o FEMUG-MA, tivemos 1 encontro até o presente momento! 
Essa semana, na quarta-feira, teremos nosso segundo encontro. Por enquanto estamos tranquilos e estamos planejando muitas coisas boas para movimentarmos nosso cenários atual.

**Comment by felipenmoura** [comment]
Essa semana rola o primeiro FEMUG-RS do ano! :)
Aqui em poa!
http://www.meetup.com/FEMUG-RS/events/228344291/
Temos 19 inscritos até então!
