### ISSUE TITLE
Criação do FEMUG-BA

### ISSUE THREAD

**Issue by mvfsilva** [femug/femug#93]
Após avaliarmos alguns aspectos, decidimos propôr o FEMUG-BA, mas por qual motivo?
Já existe um grupo no facebook chamado FrontEnd Bahia, porém ele apenas é utilizado para compartilhar links, dúvidas, etc, tendo um proposta diferente do FEMUG e estamos querendo reerguer/ressuscitar as comunidades da região. Com o FEMUG teremos encontro com a galera para realmente falarmos sobre tecnologias e conectar mais os desenvolvedores da região.

**Comment by danielfilho** [comment]
não entendi o motivo da issue.
qual a dúvida/problema?

**Comment by mvfsilva** [comment]
No doc de contribuição, pede que se abra uma issue antes de mandar PR, mas eu na minha santa lerdeza, acabei me passando e não abrir a issue.

**Comment by danielfilho** [comment]
hahaha, boa. mas nao falta só isso não cara.
vc leu duas vezes?
outra coisa, se puder fecha o PR e faz um fork novo, eu atualizei o formato do JSON hoje :)

**Comment by mvfsilva** [comment]
Cara eu li mais de 2x, então deixei passar outra coisa, mas tranquilo. Valeu!

**Comment by danielfilho** [comment]
olha os pull requests anteriores ao seu. tá tudo explícito, mas sempre da pra pegar referência dos anteriores :)
