### ISSUE TITLE
Mudança de plataforma para o FEMUG-ABC

### ISSUE THREAD

**Issue by woliveiras** [femug/femug#95]
@danielfilho, mudamos do Discourse para uma página no GitHub Pages: http://femug-abc.github.io/

Teria como apontar o abc.femug para esse novo domínio, por favor?

cc: @marquinhusgoncalves @ubirajarapelli

**Comment by danielfilho** [comment]
alterando.

pergunta: nao existe mais forum?

**Comment by woliveiras** [comment]
A galera não tem usado o esquema de Forum com o Discourse, usam mais o Slack pra interagir e o [Meetup](www.meetup.com/femug-abc/) para se inscrever, ficar sabendo de novos eventos, etc. Esquema de avisos também fazemos via Meetup por email pra todo mundo. 😄 

Nós até criamos alguns tópicos pra discussão pra incentivar, mas não virou. 😞

**Comment by danielfilho** [comment]
entao nao é legal deixar como url principal o meetup.com?

**Comment by woliveiras** [comment]
Putz, verdade cara.

Acho uma boa!

**Comment by danielfilho** [comment]
me passa a url do meetup entao que mudo lá. já tava a do blog ;)

**Comment by woliveiras** [comment]
Pra já! 

http://www.meetup.com/femug-abc/

Valeu meu querido.
